global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'tasktracker-backend'
    static_configs:
      - targets: ['backend-1:5000', 'backend-2:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-primary:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-master:6379']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
